name: Publish to PyPI

on:
  release:
    types:
      - published

permissions:
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies and build
      run: |
        python -m pip install --upgrade pip
        pip install -U build
        python -m build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
